{
	"CSEA": [{
			"organizers": "SAI TEJA.A",
			"yearBranch": "3RD CSE",
			"contact": "9441831645",
			"regFee": "30/-",
			"Sno": "1",
			"max_registrations": "80",
			"place": "INDOOR",
			"duration ": "3 hrs",
			"roomCapacity": "160",
			"emailid": "411667@student.nitandhra.ac.in",
			"event": "COLLOQUIUM",
			"noOfLevels": "3"
		},
		{
			"organizers": "A.Bhargav, Nikhila",
			"yearBranch": "4th, 3rd CSE",
			"contact": "7730033123",
			"regFee": "30/-",
			"Sno": "2",
			"max_registrations": "70",
			"place": "BOTH",
			"duration ": "2 hrs",
			"roomCapacity": "PSCP LAB and DBMS LAB",
			"emailid": "411619@student.nitandhra.ac.in",
			"event": "CRYPTACTAEON",
			"noOfLevels": "1"
		},
		{
			"organizers": "CHANDU.B",
			"yearBranch": "3RD CSE",
			"contact": "9505713598",
			"regFee": "30/-",
			"Sno": "3",
			"max_registrations": "100",
			"place": "INDOOR",
			"duration ": "3 hrs",
			"roomCapacity": "PSCP LAB and DBMS LAB",
			"emailid": "411606@student.nitandhra.ac.in",
			"event": "CODE SPRINT",
			"noOfLevels": "3"
		},
		{
			"organizers": "SHUBHAM",
			"yearBranch": "2ND CSE",
			"contact": "9441848336",
			"regFee": "NO",
			"Sno": "4",
			"max_registrations": "100",
			"place": "BOTH",
			"duration ": "ONE DAY",
			"roomCapacity": "150",
			"emailid": "subhamnitap@gmail.com",
			"event": "VIRTUALLY TRUE",
			"noOfLevels": "       - "
		}
	],
	"ECEA": [{
			"organizers": "4",
			"": "ece4c.vulcanzy19@gmail.com",
			"yearBranch": "Haritha",
			"contact": " ECE / II",
			"regFee": "100",
			"Sno": "5",
			"max_registrations": "300 on Day 1, 18 on Day2",
			"place": "FORESEE - the 4C 's",
			"duration ": "BOTH",
			"roomCapacity": "3 hrs on Day 1, 2.5 hrs on Day 2",
			"emailid": "7842655559",
			"event": "",
			"noOfLevels": "-"
		},
		{
			"organizers": "-",
			"": "ecewsvulcanzy19@gmail.com",
			"yearBranch": "Praisy, Pavani",
			"contact": "ECE / IV",
			"regFee": "150",
			"Sno": "6",
			"max_registrations": "200",
			"place": "WORKSHOP ",
			"duration ": "INDOOR",
			"roomCapacity": "3.5 hrs ",
			"emailid": "8106065197",
			"event": "",
			"noOfLevels": "-"
		},
		{
			"organizers": "-",
			"": "eceanitandhra@gmail.com",
			"yearBranch": "Aravind",
			"contact": "ECE / II",
			"regFee": "-",
			"Sno": "7",
			"max_registrations": "86 EDC Lab",
			"place": "ELECTRO WIZARD ",
			"duration ": "INDOOR",
			"roomCapacity": "3 hrs ",
			"emailid": "9440705192",
			"event": "",
			"noOfLevels": "-"
		},
		{
			"organizers": "-",
			"": "eceanitandhra@gmail.com",
			"yearBranch": "Karisma",
			"contact": "ECE / II",
			"regFee": "-",
			"Sno": "8",
			"max_registrations": "-",
			"place": "PAPER PRESENTATION",
			"duration ": "INDOOR",
			"roomCapacity": "-",
			"emailid": "7656947854",
			"event": "",
			"noOfLevels": "-"
		}
	],
	"EEEA": [{
			"organizers": "Sahithi",
			"yearBranch": "EEE/3rd",
			"contact": "7036398169",
			"regFee": "NO",
			"Sno": "9",
			"max_registrations": "50",
			"place": "INDOOR",
			"duration ": "3hrs",
			"roomCapacity": "150",
			"emailid": "ksahithi1999@gmail.com",
			"event": "ALL ABOUT CIRCUITS",
			"noOfLevels": ""
		},
		{
			"organizers": "Tanvi",
			"yearBranch": "EEE/4th ",
			"contact": "8497905584",
			"regFee": "NO",
			"Sno": "10",
			"max_registrations": "30",
			"place": "INDOOR",
			"duration ": "4hrs",
			"roomCapacity": "100",
			"emailid": "tanvigudapati@gmail.com",
			"event": "ARCHIPELAGO",
			"noOfLevels": ""
		},
		{
			"organizers": "Himaja",
			"yearBranch": "EEE/4th ",
			"contact": "8333808546",
			"regFee": "NO",
			"Sno": "11",
			"max_registrations": "50",
			"place": "INDOOR &OUTDOOR",
			"duration ": "3hrs",
			"roomCapacity": "100",
			"emailid": "himajayamasani@gmail.com",
			"event": "BACK TO THE ORIGINS",
			"noOfLevels": ""
		},
		{
			"organizers": "Sravya",
			"yearBranch": "EEE/4th ",
			"contact": "8330971998",
			"regFee": "NO",
			"Sno": "12",
			"max_registrations": "60",
			"place": "INDOOR",
			"duration ": "3hrs",
			"roomCapacity": "100",
			"emailid": "agsravya@gmail.com",
			"event": "AMALGAMATE",
			"noOfLevels": ""
		},
		{
			"organizers": "Vishnu ",
			"yearBranch": "EEE/4th ",
			"contact": "8089442725",
			"regFee": "NO",
			"Sno": "13",
			"max_registrations": "50",
			"place": "INDOOR",
			"duration ": "4hrs",
			"roomCapacity": "100",
			"emailid": "vishnu.ajayan08@gmail.com",
			"event": "DECEPTION",
			"noOfLevels": ""
		},
		{
			"organizers": "Satish",
			"yearBranch": "EEE/4th ",
			"contact": "7780144689",
			"regFee": "",
			"Sno": "14",
			"max_registrations": "",
			"place": "INDOOR",
			"duration ": "….",
			"roomCapacity": "",
			"emailid": "sgaur016@gmail.com",
			"event": "PROJECT EXPO",
			"noOfLevels": ""
		},
		{
			"organizers": "Surendra",
			"yearBranch": "EEE/3rd",
			"contact": "8179060324",
			"regFee": "",
			"Sno": "15",
			"max_registrations": "",
			"place": "INDOOR",
			"duration ": "….",
			"roomCapacity": "",
			"emailid": "surendrasrinivasmali@gmail.com",
			"event": "PAPER PRESENTATION",
			"noOfLevels": ""
		}
	],
	"CEA": [{
			"organizers": "N Vikshay rao",
			"yearBranch": "",
			"contact": "9491657359",
			"regFee": "250/-",
			"Sno": "16",
			"max_registrations": "20",
			"place": "INDOOR",
			"duration ": "24x3",
			"roomCapacity": "100+",
			"emailid": "vikshayrao@gmail.com",
			"event": "Civilopedia",
			"noOfLevels": "1"
		},
		{
			"organizers": "V Arundhathi",
			"yearBranch": "",
			"contact": "9133416931",
			"regFee": "250/-",
			"Sno": "17",
			"max_registrations": "40",
			"place": "DBMS Lab",
			"duration ": "2hrs",
			"roomCapacity": "40",
			"emailid": "arundhathivantepaka@gmail.com",
			"event": "Crack The Structure",
			"noOfLevels": "1"
		},
		{
			"organizers": "K.Vindhya",
			"yearBranch": "",
			"contact": "9550260017",
			"regFee": "250/-",
			"Sno": "18",
			"max_registrations": "40",
			"place": "Concrete lab/Outdoor",
			"duration ": "3hrs",
			"roomCapacity": "30",
			"emailid": "vindhya.vamsy@gmail.com",
			"event": "Con-Create",
			"noOfLevels": "1"
		},
		{
			"organizers": "S Manasa",
			"yearBranch": "",
			"contact": "9490169522",
			"regFee": "NIL",
			"Sno": "19",
			"max_registrations": "30",
			"place": "INDOOR",
			"duration ": "3hrs",
			"roomCapacity": "70+",
			"emailid": "sreeram.n.l.manasa@gmail.com",
			"event": "Paperesento",
			"noOfLevels": "1"
		},
		{
			"organizers": "J Sri Harika",
			"yearBranch": "_",
			"contact": "7981612613",
			"regFee": "NIL",
			"Sno": "20",
			"max_registrations": "Not Restricted",
			"place": "INDOOR",
			"duration ": "2hrs",
			"roomCapacity": "100+",
			"emailid": "jajulasriharika08@gmail.com",
			"event": "Ask me Anything",
			"noOfLevels": "3"
		},
		{
			"organizers": "Y Satyavani",
			"yearBranch": "",
			"contact": "8886362609",
			"regFee": "250/-",
			"Sno": "21",
			"max_registrations": "30",
			"place": "INDOOR",
			"duration ": "3hrs",
			"roomCapacity": "40",
			"emailid": "satyavaniyerra33@gmail.com",
			"event": "Ville Intelligente",
			"noOfLevels": "1"
		}
	],
	"MEA": [{
			"organizers": "vikash Kumar ray",
			"yearBranch": "MME/3",
			"contact": "7903292972",
			"regFee": "30",
			"Sno": "22",
			"max_registrations": "50",
			"place": "OUTDOOR  ",
			"duration ": " 3 hrs",
			"roomCapacity": "open lawn",
			"emailid": "raushanlki98@gmail.com",
			"event": "One Thrust 2.0",
			"noOfLevels": "3"
		},
		{
			"organizers": "O.Praneeth ",
			"yearBranch": "MME/4",
			"contact": "+91 97050 31849",
			"regFee": "20",
			"Sno": "23",
			"max_registrations": "80",
			"place": "indoor",
			"duration ": "day 1 : 1 hour\nday 2:   1 hour",
			"roomCapacity": "~100",
			"emailid": "opraneethreddy@gmail.com",
			"event": "Riddle hurdles",
			"noOfLevels": "3"
		},
		{
			"organizers": "M Sritejaswini",
			"yearBranch": "MME/3",
			"contact": "9492000486",
			"regFee": "no fee for NIT andhra students ",
			"Sno": "24",
			"max_registrations": "30, for outsiders: 20",
			"place": "OUTDOOR",
			"duration ": "4 hrs",
			"roomCapacity": "open lawn",
			"emailid": "msritejaswini@gmail.com ",
			"event": "Wax mock-up",
			"noOfLevels": "1"
		},
		{
			"organizers": "S.Vinod Kumar",
			"yearBranch": "MME/3",
			"contact": "7013281210",
			"regFee": "10",
			"Sno": "25",
			"max_registrations": "40",
			"place": "indoor",
			"duration ": "day 1,2: 1 hr",
			"roomCapacity": "room ~ 80",
			"emailid": "sabavathvinodkumar60@gmail.com",
			"event": "What's beyond",
			"noOfLevels": "2"
		}
	],
	"BIOTECH": [{
			"organizers": "Pilli Akhil",
			"yearBranch": "3rd year",
			"contact": "7661876146",
			"regFee": "10/ person ",
			"Sno": "26",
			"max_registrations": "200",
			"place": "Indoor",
			"duration ": "4 hrs",
			"roomCapacity": "700+",
			"emailid": "bea.nitap@gmail.com ",
			"event": "Forensics v2",
			"noOfLevels": "3"
		},
		{
			"organizers": "Sree Raj Akhil",
			"yearBranch": "2nd year",
			"contact": "7702290359",
			"regFee": "20/group ",
			"Sno": "27",
			"max_registrations": "100",
			"place": "outdoor ",
			"duration ": "2 hours",
			"roomCapacity": "nill",
			"emailid": "bea.nitap@gmail.com",
			"event": "Garden scavengers ",
			"noOfLevels": "1"
		},
		{
			"organizers": "J. Roshini",
			"yearBranch": "4th year ",
			"contact": "",
			"regFee": "NIL",
			"Sno": "28",
			"max_registrations": "50",
			"place": "Indoor",
			"duration ": "2 hours",
			"roomCapacity": "100+",
			"emailid": "bea.nitap@gmail.com",
			"event": "Lumiere",
			"noOfLevels": "2"
		}
	],
	"MECH": [{
			"organizers": "Saurav",
			"yearBranch": "Mech III",
			"contact": "7739465809",
			"regFee": "500 / team",
			"Sno": "29",
			"max_registrations": "8 teams",
			"place": "Outdoor",
			"duration ": "4 hrs",
			"roomCapacity": "      _",
			"emailid": "anshusingh21198@gmail.com",
			"event": "AMMC(Aircraft Modelling and Maneuvering Challange)",
			"noOfLevels": ""
		},
		{
			"organizers": "N.B.R Kaushik",
			"yearBranch": "Mech III",
			"contact": "9441282580",
			"regFee": "",
			"Sno": "30",
			"max_registrations": "       -",
			"place": "Indoor",
			"duration ": "4 hrs",
			"roomCapacity": "60",
			"emailid": "kkaushi7@gmail.com",
			"event": "GISS(Godavari Innovation for Society Summit)",
			"noOfLevels": ""
		},
		{
			"organizers": "Yogesh",
			"yearBranch": "Mech II",
			"contact": "9130633135",
			"regFee": "nil",
			"Sno": "31",
			"max_registrations": "15 teams",
			"place": "Indoor",
			"duration ": "4 hrs",
			"roomCapacity": "50-60",
			"emailid": "Patilmapari@gmail.com",
			"event": "MARC(Mechanism and Robotics Championship)",
			"noOfLevels": ""
		},
		{
			"organizers": "M.Saikiran",
			"yearBranch": "Mech III",
			"contact": "9182289736",
			"regFee": "200/team",
			"Sno": "32",
			"max_registrations": "15 teams",
			"place": "indoor",
			"duration ": "4 hrs",
			"roomCapacity": "50-60",
			"emailid": "saikiranmallembakam15@gmail.com",
			"event": "Robo-War",
			"noOfLevels": ""
		},
		{
			"organizers": "K.Spandan",
			"yearBranch": "Mech III",
			"contact": "9490090209",
			"regFee": "nil",
			"Sno": "33",
			"max_registrations": "        -",
			"place": "Indoor",
			"duration ": "3 hrs",
			"roomCapacity": "50-60",
			"emailid": "spandan2344@gmail.com",
			"event": "Workshop&Quizzes",
			"noOfLevels": ""
		}
	],
	"MUSIC": [{
			"organizers": "Swaroopa ",
			"yearBranch": "EEE /4th yr",
			"contact": "8374411375",
			"regFee": "50",
			"Sno": "34",
			"max_registrations": "100",
			"place": "indoor",
			"duration ": "3 hours /2days",
			"roomCapacity": "70-80 people ",
			"emailid": "swaroopawendly37@gmail.com",
			"event": "Talent hunt ",
			"noOfLevels": ""
		},
		{
			"organizers": "Kiranmayi ",
			"yearBranch": "Biotech /3rd Yr ",
			"contact": "9493744988",
			"regFee": "50",
			"Sno": "35",
			"max_registrations": "80",
			"place": "indoor",
			"duration ": "3hours ",
			"roomCapacity": "70-80",
			"emailid": "kiranmaipulya@gmail.com ",
			"event": "lyrical maestro ",
			"noOfLevels": ""
		},
		{
			"organizers": "Uday ",
			"yearBranch": "civil /3rd Yr ",
			"contact": "9515570887",
			"regFee": "50",
			"Sno": "36",
			"max_registrations": "70",
			"place": "indoor ",
			"duration ": "3hours ",
			"roomCapacity": "50-60",
			"emailid": "udaykumarteegala@gmail.com",
			"event": "Guess it Win it ",
			"noOfLevels": ""
		},
		{
			"organizers": "Unnathi ",
			"yearBranch": "Ece /3rd Yr ",
			"contact": "9110528561",
			"regFee": "",
			"Sno": "37",
			"max_registrations": "70",
			"place": "online ",
			"duration ": "one level ",
			"roomCapacity": "",
			"emailid": "unnathi.c@gmail.com",
			"event": "Instagram vedios ",
			"noOfLevels": ""
		}
	],
	"PNP": [{
			"organizers": "Sai Kiran,Appala Reddy,Vishal",
			"yearBranch": "3rd year,1st year,1st year   ",
			"contact": "9182289736",
			"regFee": "20",
			"Sno": "38",
			"max_registrations": "100",
			"place": "INDOOR",
			"duration ": "3 hours",
			"roomCapacity": "150-200",
			"emailid": "pnpnitap@gmail.com",
			"event": "Hand Painting",
			"noOfLevels": "0"
		},
		{
			"organizers": "Santhoshi,Praneesh,Ramya",
			"yearBranch": "2nd year,1st year,1st year",
			"contact": "7093567225",
			"regFee": "nil",
			"Sno": "39",
			"max_registrations": "60",
			"place": "INDOOR",
			"duration ": "3 hours",
			"roomCapacity": "50-60",
			"emailid": "pnpnitap@gmail.com",
			"event": "Art in Line",
			"noOfLevels": "0"
		},
		{
			"organizers": "Khyathi Aneesha,Tanmayi",
			"yearBranch": "3rd year,2nd year",
			"contact": "7995956499",
			"regFee": "nil",
			"Sno": "40",
			"max_registrations": "50",
			"place": "INDOOR",
			"duration ": "3 hours ",
			"roomCapacity": "50-60",
			"emailid": "pnpnitap@gmail.com",
			"event": "ART-A-THON",
			"noOfLevels": "2"
		},
		{
			"organizers": "Nivas,Vani,Navya",
			"yearBranch": "3rd year,2nd year,1st year",
			"contact": "7893935978",
			"regFee": "nil",
			"Sno": "41",
			"max_registrations": "60",
			"place": "INDOOR",
			"duration ": "3 hours",
			"roomCapacity": "50-60",
			"emailid": "pnpnitap@gmail.com",
			"event": "Paint Without Brush",
			"noOfLevels": "0"
		},
		{
			"organizers": "Nitin,Tarun,Aman rao",
			"yearBranch": "3rd year,4th year,2nd year",
			"contact": "9490271374",
			"regFee": "nil",
			"Sno": "42",
			"max_registrations": "",
			"place": "INDOOR",
			"duration ": "1 hour( for showing ads)",
			"roomCapacity": "150-200",
			"emailid": "pnpnitap@gmail.com",
			"event": "Ad making competition",
			"noOfLevels": "0"
		},
		{
			"organizers": "Nuthan,Jithendreswar,Azharuddin",
			"yearBranch": "4th year,3rd year,2nd year",
			"contact": "9492230494",
			"regFee": "nil",
			"Sno": "43",
			"max_registrations": "",
			"place": "",
			"duration ": "ONLINE event",
			"roomCapacity": "",
			"emailid": "pnpnitap@gmail.com",
			"event": "Photo contest",
			"noOfLevels": "0"
		},
		{
			"organizers": "Vikas,Bhardwaj,Shiva",
			"yearBranch": "3rd year,3rd year,2nd year",
			"contact": "9292755807",
			"regFee": "nil",
			"Sno": "44",
			"max_registrations": "",
			"place": "",
			"duration ": "ONLINE event",
			"roomCapacity": "",
			"emailid": "pnpnitap@gmail.com",
			"event": "mannequin_challenge",
			"noOfLevels": "0"
		}
	],
	"MAGAZINE": [{
			"organizers": "M.Monica,K.V.R Yashwant",
			"yearBranch": "3",
			"contact": "9502593474/7675022428",
			"regFee": "-",
			"Sno": "46",
			"max_registrations": "unlimited",
			"place": "online",
			"duration ": "-",
			"roomCapacity": "-",
			"emailid": "monicamatta999@gmail.com",
			"event": "Bookfie",
			"noOfLevels": "1"
		},
		{
			"organizers": "Mubeen, Manjunadh, Srilekha ",
			"yearBranch": "3",
			"contact": "8184883793/9951540702/9494291402",
			"regFee": "-",
			"Sno": "47",
			"max_registrations": "100-120",
			"place": "indoor",
			"duration ": "30 min ",
			"roomCapacity": "100-120",
			"emailid": "manjunadhreddyjampana@gmail.com",
			"event": "Illusion",
			"noOfLevels": "1"
		}
	],
	"SNH": [{
			"organizers": "KETAN BANSAL",
			"yearBranch": "CSE-1",
			"contact": "6264079466",
			"regFee": "50/team",
			"Sno": "48",
			"max_registrations": "25",
			"place": "INDOOR",
			"duration ": "4 hrs",
			"roomCapacity": "100",
			"emailid": "ketan.bansal255@gmail.com",
			"event": "BEST OUT OF WASTE",
			"noOfLevels": ""
		},
		{
			"organizers": "UMESH YADAV",
			"yearBranch": "CSE-3",
			"contact": "8789853068",
			"regFee": "50/person",
			"Sno": "49",
			"max_registrations": "50",
			"place": "OUTDOOR",
			"duration ": "3-4 hrs",
			"roomCapacity": "NOT REQUIRED",
			"emailid": "umeshyadav1997@gmail.com",
			"event": "LAZY HOVER V1.0",
			"noOfLevels": ""
		},
		{
			"organizers": "RITURAJ SINGH SUJAWAT",
			"yearBranch": "CIVIL-3",
			"contact": "7597575752",
			"regFee": "50/person",
			"Sno": "50",
			"max_registrations": "Nil",
			"place": "INDOOR",
			"duration ": "1 day",
			"roomCapacity": "25",
			"emailid": "riturajsinghsujawat@gmail.com",
			"event": "Van De Graff Generator",
			"noOfLevels": ""
		},
		{
			"organizers": "P N S MEGHANA",
			"yearBranch": "ECE-2",
			"contact": "9063033023",
			"regFee": "50/team",
			"Sno": "51",
			"max_registrations": "100",
			"place": "INDOOR",
			"duration ": "2-3 hrs",
			"roomCapacity": "200",
			"emailid": "pnsmeghana@gmail.com",
			"event": "LANTERN MAKING",
			"noOfLevels": ""
		},
		{
			"organizers": "SRAVYA D",
			"yearBranch": "CIVIL-4",
			"contact": "9490597205",
			"regFee": "100 /team",
			"Sno": "52",
			"max_registrations": "100",
			"place": "BOTH",
			"duration ": "1 day",
			"roomCapacity": "200",
			"emailid": "d.v.s.s.bhuvanasravya@gmail.com",
			"event": "RUN TO WIN",
			"noOfLevels": ""
		}
	],
	"DND": [{
			"organizers": "Shreyas, Akhilesh",
			"yearBranch": "1st yr, 2nd yr",
			"contact": "6204828580, 8367229807",
			"regFee": "-",
			"Sno": "53",
			"max_registrations": "no limit",
			"place": "indoor(online)",
			"duration ": "-",
			"roomCapacity": "-",
			"emailid": "ssahay3105@gmail.com, boinapallyabhi@gmail.com",
			"event": "MEME-finity war",
			"noOfLevels": ""
		},
		{
			"organizers": "Supriya, Akash",
			"yearBranch": "3rd yr, 2nd yr",
			"contact": "8143686771, 9834015455",
			"regFee": "-",
			"Sno": "54",
			"max_registrations": "no limit",
			"place": "indoor(online)",
			"duration ": "4-8sec",
			"roomCapacity": "",
			"emailid": ", akashsuryawanshi328@gmail.com",
			"event": "Boomerang",
			"noOfLevels": ""
		},
		{
			"organizers": "Sai pavan, Sandeep gajula",
			"yearBranch": "2nd yr, 2nd yr",
			"contact": "8096986594, 6304214136",
			"regFee": "-",
			"Sno": "55",
			"max_registrations": "no limit",
			"place": "indoor",
			"duration ": "-",
			"roomCapacity": "",
			"emailid": "saipavanraja99@gmail.com, sangajula20@gmail.com",
			"event": "Tell a Tale",
			"noOfLevels": ""
		},
		{
			"organizers": "Divya Ashish, Gayatri",
			"yearBranch": "2nd year, 3rd year",
			"contact": "7909041287, 9490039009",
			"regFee": "-",
			"Sno": "56",
			"max_registrations": "no limit",
			"place": "indoor",
			"duration ": "10-15 min",
			"roomCapacity": "",
			"emailid": "divyaashishkat@gmail.com, vlpg98@yahoo.in",
			"event": "Short film",
			"noOfLevels": ""
		},
		{
			"organizers": "Komali, Lahari",
			"yearBranch": "2nd yr, 3rd yr",
			"contact": "9121511312, 9963037253",
			"regFee": "-",
			"Sno": "57",
			"max_registrations": "no limit",
			"place": "indoor",
			"duration ": "first round (12-03-19) - 3hrs , second round (14-03-19) - 1hr",
			"roomCapacity": "",
			"emailid": "komalip97@gmail.com, laharigadili@gmail.com",
			"event": "Dance competition",
			"noOfLevels": ""
		},
		{
			"organizers": "Charan , Utkarsh",
			"yearBranch": "3rd yr, 2nd yr",
			"contact": "9440894279, 9695605859",
			"regFee": "-",
			"Sno": "58",
			"max_registrations": "no limit",
			"place": "indoor",
			"duration ": "first round (11-03-19) - 3hrs , second round (14-03-19) - 1hr",
			"roomCapacity": "",
			"emailid": "yeddulacharankumarreddy1999@gmail.com,",
			"event": "Drama competition",
			"noOfLevels": ""
		}
	]
}